default['oreno']['base_dir'] = '/opt/oreno'
default['oreno']['mysql_version']   = '5.7'
default['oreno']['datadir']   = '/var/lib/mysql'
default['oreno']['socket']    = '/var/lib/mysql/mysql.sock'
default['oreno']['log-error'] = '/var/log/mysqld.log'
default['oreno']['pid-file']  = '/var/run/mysqld/mysqld.pid'
default['oreno']['type']      = 'master'
